#!/bin/sh
# Shipyard Installation Script for FreeBSD
# This script installs all requirements and sets up Shipyard

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
    printf "${GREEN}[INFO]${NC} %s\n" "$1"
}

log_warn() {
    printf "${YELLOW}[WARN]${NC} %s\n" "$1"
}

log_error() {
    printf "${RED}[ERROR]${NC} %s\n" "$1"
}

# Check if running as root
if [ "$(id -u)" -ne 0 ]; then
    log_error "This script must be run as root"
    exit 1
fi

# Detect FreeBSD version
FREEBSD_VERSION=$(freebsd-version -u | cut -d'-' -f1)
log_info "Detected FreeBSD version: ${FREEBSD_VERSION}"

# ============================================================================
# Stop existing services (for reinstall)
# ============================================================================
if service shipyard status >/dev/null 2>&1; then
    log_info "Stopping existing Shipyard service..."
    service shipyard stop || true
fi

if service nginx status >/dev/null 2>&1; then
    log_info "Stopping nginx..."
    service nginx stop || true
fi

# ============================================================================
# Install packages
# ============================================================================
log_info "Updating pkg repository..."
pkg update -f

log_info "Installing required packages..."
pkg install -y \
    nginx \
    go \
    git \
    py311-certbot \
    ca_root_nss \
    pot

# ============================================================================
# Create directories
# ============================================================================
log_info "Creating directories..."

# Shipyard directories
mkdir -p /usr/local/etc/shipyard
mkdir -p /var/log/shipyard
mkdir -p /var/run

# Nginx directories
mkdir -p /usr/local/etc/nginx/sites-available
mkdir -p /usr/local/etc/nginx/sites-enabled
mkdir -p /var/log/nginx

# Jail directories
mkdir -p /var/jails
mkdir -p /var/cache/shipyard

# Let's Encrypt directories
mkdir -p /usr/local/etc/letsencrypt

# ============================================================================
# Build and install Shipyard
# ============================================================================
log_info "Building Shipyard..."

# Create temp directory for build
BUILD_DIR=$(mktemp -d)
cd "${BUILD_DIR}"

# Check if we're installing from local source or git
if [ -d "/usr/local/src/shipyard" ]; then
    log_info "Building from /usr/local/src/shipyard..."
    cd /usr/local/src/shipyard
elif [ -n "${SHIPYARD_REPO}" ]; then
    log_info "Cloning from ${SHIPYARD_REPO}..."
    git clone "${SHIPYARD_REPO}" shipyard
    cd shipyard
else
    log_warn "No source found. Please either:"
    log_warn "  1. Place source code in /usr/local/src/shipyard"
    log_warn "  2. Set SHIPYARD_REPO environment variable"
    log_warn "  3. Copy the shipyard binary to /usr/local/bin/shipyard manually"
    log_warn ""
    log_warn "Skipping build step..."
    SKIP_BUILD=1
fi

if [ -z "${SKIP_BUILD}" ]; then
    # Build the binary
    go build -o shipyard .

    # Install binary
    install -m 755 shipyard /usr/local/bin/shipyard
    log_info "Installed shipyard to /usr/local/bin/shipyard"
fi

# Clean up build directory
cd /
rm -rf "${BUILD_DIR}"

# ============================================================================
# Generate default configuration
# ============================================================================
if [ ! -f /usr/local/etc/shipyard/shipyard.toml ]; then
    log_info "Creating default configuration..."

    # Generate a random admin key
    ADMIN_KEY="sk-admin-$(head -c 32 /dev/urandom | sha256 | head -c 40)"

    cat > /usr/local/etc/shipyard/shipyard.toml << EOF
# Shipyard configuration
# Generated by install.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Admin API key - CHANGE THIS!
admin_keys = [
    "${ADMIN_KEY}",
]

[server]
listen_addr = "127.0.0.1:8443"
log_file    = "/var/log/shipyard/shipyard.log"

[nginx]
binary_path     = "/usr/local/sbin/nginx"
main_conf_path  = "/usr/local/etc/nginx/nginx.conf"
sites_available = "/usr/local/etc/nginx/sites-available"
sites_enabled   = "/usr/local/etc/nginx/sites-enabled"
override_conf   = "/usr/local/etc/nginx/override.conf"

[jail]
binary_path     = "/usr/local/bin/pot"
base_dir        = "/var/jails"
jail_conf_path  = "/etc/jail.conf"
freebsd_version = "${FREEBSD_VERSION}"
tarball_cache   = "/var/cache/shipyard/base.txz"
ip_base         = "127.0.1"

[health]
poll_interval     = "15s"
failure_threshold = 3
health_path       = "/health"

[self]
binary_path = "/usr/local/bin/shipyard"
pid_file    = "/var/run/shipyard.pid"
config_dir  = "/usr/local/etc/shipyard"

# Default site (rename and customize for your use)
[site.default]
domain        = "localhost"
frontend_root = "/usr/local/www/default"
api_key       = "$(head -c 20 /dev/urandom | sha256 | head -c 40)"
override_ips  = ["127.0.0.1", "::1"]
EOF

    chmod 600 /usr/local/etc/shipyard/shipyard.toml
    log_info "Configuration created at /usr/local/etc/shipyard/shipyard.toml"
    log_warn "IMPORTANT: Edit the configuration and change the admin key!"
else
    log_info "Configuration already exists, skipping..."
fi

# ============================================================================
# Generate nginx main config
# ============================================================================
log_info "Configuring nginx..."

cat > /usr/local/etc/nginx/nginx.conf << 'EOF'
# MANAGED BY SHIPYARD - DO NOT EDIT
worker_processes auto;
error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    access_log  /var/log/nginx/access.log combined;

    sendfile        on;
    tcp_nopush      on;
    keepalive_timeout  65;

    # Allow large uploads for deployments (500MB)
    client_max_body_size 500M;

    # Override subsystem (map/geo blocks) - regenerated by shipyard
    include /usr/local/etc/nginx/override.conf;

    # Per-site server blocks - user-provided
    include /usr/local/etc/nginx/sites-enabled/*.conf;
}
EOF

# Create/overwrite override.conf (managed by Shipyard)
cat > /usr/local/etc/nginx/override.conf << 'EOF'
# MANAGED BY SHIPYARD - DO NOT EDIT
# This file will be regenerated when sites are deployed

map $arg_override $frontend_version {
    default      latest;
    ~.+          $arg_override;
}

map $arg_override $is_override {
    default  0;
    ~.+      1;
}

map $is_override $xrobots_value {
    default  "";
    1        "noindex, nofollow";
}
EOF

# ============================================================================
# Create rc.d service script
# ============================================================================
log_info "Creating rc.d service script..."

cat > /usr/local/etc/rc.d/shipyard << 'EOF'
#!/bin/sh

# PROVIDE: shipyard
# REQUIRE: LOGIN networking nginx
# KEYWORD: shutdown

. /etc/rc.subr

name="shipyard"
rcvar="shipyard_enable"
desc="Shipyard deployment framework"

load_rc_config $name

: ${shipyard_enable:="NO"}
: ${shipyard_config:="/usr/local/etc/shipyard/shipyard.toml"}
: ${shipyard_user:="root"}

pidfile="/var/run/${name}.pid"
command="/usr/local/bin/shipyard"
command_args="serve --config ${shipyard_config}"

start_cmd="${name}_start"
stop_cmd="${name}_stop"
status_cmd="${name}_status"

shipyard_start()
{
    if [ -f "${pidfile}" ]; then
        pid=$(cat "${pidfile}")
        if kill -0 "${pid}" 2>/dev/null; then
            echo "${name} is already running (pid ${pid})"
            return 1
        fi
        rm -f "${pidfile}"
    fi

    echo "Starting ${name}..."
    /usr/sbin/daemon -P "${pidfile}" -r -f -u "${shipyard_user}" \
        ${command} ${command_args}
}

shipyard_stop()
{
    if [ -f "${pidfile}" ]; then
        pid=$(cat "${pidfile}")
        echo "Stopping ${name} (pid ${pid})..."
        kill "${pid}" 2>/dev/null
        rm -f "${pidfile}"
    else
        echo "${name} is not running"
    fi
}

shipyard_status()
{
    if [ -f "${pidfile}" ]; then
        pid=$(cat "${pidfile}")
        if kill -0 "${pid}" 2>/dev/null; then
            echo "${name} is running (pid ${pid})"
            return 0
        fi
    fi
    echo "${name} is not running"
    return 1
}

run_rc_command "$1"
EOF

chmod 755 /usr/local/etc/rc.d/shipyard

# ============================================================================
# Initialize pot (for backend services)
# ============================================================================
if command -v pot >/dev/null 2>&1; then
    if [ ! -d /opt/pot ]; then
        log_info "Initializing pot..."
        pot init || log_warn "pot init failed - configure /usr/local/etc/pot/pot.conf manually if you need backend services"
    fi

    # Create base pot for the current FreeBSD version if it doesn't exist
    POT_BASE_VERSION=$(echo "${FREEBSD_VERSION}" | cut -d'.' -f1-2)
    if ! pot ls -b 2>/dev/null | grep -q "^${POT_BASE_VERSION}$"; then
        log_info "Creating pot base for FreeBSD ${POT_BASE_VERSION}..."
        pot create-base -r "${POT_BASE_VERSION}" || log_warn "pot create-base failed - you may need to create it manually"
    fi
fi

# ============================================================================
# Enable services
# ============================================================================
log_info "Enabling services..."

sysrc nginx_enable="YES"
sysrc shipyard_enable="YES"

# ============================================================================
# Start services
# ============================================================================
log_info "Starting nginx..."
service nginx start 2>/dev/null || service nginx restart

# ============================================================================
# Install Helm control panel as default site
# ============================================================================
log_info "Installing Helm control panel..."

# Clean up old installation
rm -rf /usr/local/www/default/latest
mkdir -p /usr/local/www/default/latest

if [ -d "/usr/local/src/shipyard/web/dist" ]; then
    cp -r /usr/local/src/shipyard/web/dist/* /usr/local/www/default/latest/
else
    # Create a minimal placeholder if web/dist not available
    cat > /usr/local/www/default/latest/index.html << 'HTMLEOF'
<!DOCTYPE html>
<html>
<head><title>Shipyard</title></head>
<body>
<h1>Shipyard</h1>
<p>Helm control panel not built. Run <code>cd web && npm run build</code> and reinstall.</p>
</body>
</html>
HTMLEOF
fi

# Create nginx config for Helm control panel
cat > /usr/local/etc/nginx/sites-available/default.conf << 'EOF'
server {
    listen 80 default_server;
    server_name _;
    root /usr/local/www/default/latest;
    index index.html;

    # Proxy API requests to local Shipyard server
    location /api/ {
        proxy_pass http://127.0.0.1:8443/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        client_max_body_size 500m;
        proxy_request_buffering off;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|png|jpg|gif|svg|woff2?)$ {
        expires 30d;
        add_header Cache-Control "public, immutable";
    }
}
EOF

ln -sf /usr/local/etc/nginx/sites-available/default.conf /usr/local/etc/nginx/sites-enabled/default.conf
service nginx reload

# Clean up stale PID file and start Shipyard
rm -f /var/run/shipyard.pid
log_info "Starting Shipyard..."
service shipyard start

# ============================================================================
# Print summary
# ============================================================================
echo ""
echo "============================================================================"
echo "  Shipyard Installation Complete"
echo "============================================================================"
echo ""
echo "  Configuration: /usr/local/etc/shipyard/shipyard.toml"
echo "  Logs:          /var/log/shipyard/shipyard.log"
echo "  Nginx logs:    /var/log/nginx/"
echo ""
echo "  Helm control panel: http://localhost/"
echo ""
echo "  Next steps:"
echo ""
echo "  1. Open Helm in your browser and connect with your admin key"
echo ""
if [ -n "${ADMIN_KEY}" ]; then
echo "  Your generated admin key (save this!):"
echo "     ${ADMIN_KEY}"
echo ""
fi
echo "============================================================================"
